stages:
- build
- run

variables:
    GIT_SUBMODULE_STRATEGY: recursive

build:
    stage: build
    image: ubuntu
    before_script:
    - apt update
    - apt install gcc cmake ninja-build gcovr -y
    script:
    - CC=gcc cmake . -Bbuild -GNinja
    - cd build
    - cmake --build . --config Debug
    artifacts:
        paths:
        - build/lab

run:
    stage: run
    image: ubuntu
    before_script:
    - apt update
    - apt install gcovr -y
    script:
    - cd build
    - ./lab -f ../test/test1.lab
    - gcovr