stages:
- build
- run

variables:
    GIT_SUBMODULE_STRATEGY: recursive

build:
    stage: build
    image: ubuntu
    before_script:
    - apt update
    - apt install gcc cmake ninja-build -y
    script:
    - CC=gcc cmake . -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Debug
    - cd build
    - cmake --build . --config Debug
    artifacts:
        paths:
        - build/lab
        - build/CMakeFiles/lab.dir/src/*.o
        - build/CMakeFiles/lab.dir/src/*.gcno

run:
    stage: run
    image: ubuntu
    before_script:
    - apt update
    - apt install python3-pip -y
    - pip3 --version
    - pip3 install gcovr
    script:
    - cd build
    - ./lab -f ../test/runtest.lab -d
    - gcovr