program -> declaration* EOF ;

statement -> exprStmt
           | forStmt
           | ifStmt
           | returnStmt
           | whileStmt
           | block ;

exprStmt -> expression ";" ;
block    -> "{" declaration* "}" ;
